### ISSUE TITLE
Add more built-in functions in default_env.gd

### ISSUE THREAD

**Issue by Ark2000** [Ark2000/PankuConsole#1]
For examples,
`show_fps()` will allow to add a label on the top left screen displaying current frame rate.
`fullscreen()` will allow to make the game fullscreen

These simple functions would be very convenient.

**Comment by scriptsengineer** [comment]
Would the idea of putting FPS information be static? I believe it would be useful to have another window with status, which can be added and removed

**Comment by Ark2000** [comment]
> Would the idea of putting FPS information be static? I believe it would be useful to have another window with status, which can be added and removed

Nice suggestion. I'm considering adding floating widgets so we can monitor an expression's value at a constant frequency.
