### ISSUE TITLE
Bug: Empty symbols instead of Emoji

### ISSUE THREAD

**Issue by Loregret** [Ark2000/PankuConsole#112]
**Describe the bug**
I have no emoji in console logs. [RichText doesn't support Emoji by default](https://docs.godotengine.org/en/latest/tutorials/ui/gui_using_fonts.html#using-emoji)

**Screenshots**
![Screenshot_20230621_124447](https://github.com/Ark2000/PankuConsole/assets/31369647/f514ae46-f4ee-401c-bd1b-fc29a2a130b4)

**Comment by Ark2000** [comment]
What is your operating system?

**Comment by Loregret** [comment]
> What is your operating system?

Linux OpenSUSE

**Comment by Ark2000** [comment]
Emoji introduction got removed in the latest release, it's more concise now.

![image](https://github.com/Ark2000/PankuConsole/assets/21126555/89d89969-4ffa-4f44-a724-2f73cbb71c71)
