### ISSUE TITLE
Editor freezes on quit when plugin is enabled

### ISSUE THREAD

**Issue by francoisdlt** [Ark2000/PankuConsole#114]
**Describe the bug**
When the plugin is enabled and I quit the editor, it freezes and stops responding

**To Reproduce**
1. create new project
2. add panku_console plugin
3. enable panku_console plugin
4. quit the editor

**Expected behavior**
the editor should quit normally

**Desktop:**
 - OS: macOS 13.4.1 on ARM M2 architecture
 - Editor : Godot 4.1 stable
- plugin version : 1.5.162

**Additional context**
I still get the "Panku Console unloaded" message before it freezes
Whenever I disable the plugin, the problem disappears.

**Comment by Ark2000** [comment]
what about the latest commit?

**Comment by Ark2000** [comment]
sorry i dont have a mac machine, the only code piece i can think of is the `_exit_tree` function in `plugin.gd`, you can comment out that function to see if it works. also, try to run godot in verbose mode to get more detailed engine logs, i solved a lot of problems by reading that.

**Comment by francoisdlt** [comment]
Following your suggestion, I found that commenting the `print` instruction solves the issue.

**Comment by Ark2000** [comment]
> Following your suggestion, I found that commenting the `print` instruction solves the issue.

weird, but thankfully it works.

**Comment by Ark2000** [comment]
it is an Engine bug introduced by 4.1, confirmed on windows too.

**Comment by Ark2000** [comment]
`_exit_tree()` function was removed and now it should works well.

**Comment by francoisdlt** [comment]
thanks ! does the mirror repository update automatically ?

**Comment by Ark2000** [comment]
> thanks ! does the mirror repository update automatically ?

unfortunately not, but I'll later work on this, and I have to manually update mirror repo until now.

**Comment by Ark2000** [comment]
https://github.com/Ark2000/PankuConsole/issues/119

**Comment by francoisdlt** [comment]
I confirm the freeze is gone with the new version and thanks for updating the mirror repo !
