### ISSUE TITLE
Widgets system

### ISSUE THREAD

**Issue by Ark2000** [Ark2000/PankuConsole#12]
![image](https://user-images.githubusercontent.com/21126555/203830683-a22cfee5-f26e-44d0-8a7a-c1673f86e2a9.png)

I came up with this idea from the conversation with @scriptsengineer : https://github.com/Ark2000/PankuConsole/issues/1

You can create floating widgets very quickly inside the console or in your code, they are capable of:
1.  being closed with a close icon.
2.  being dragged around and snap to the screen edge just like the console window.
3.  being clicked and then execute an expression.
4.  being update by an expression at a constant frequency.

There will be something maybe a manager window to manage multiple widgets plans and autoload widgets, more details will be explained later.

This feature will be of great help Imo since you can monitor expressions and call expressions conveniently.

# More details

The whole system can be fully accessed inside the console.
More specifically, I added several functions in `default_env.gd`, explained below:

```gdscript
#Add a widget to watch an expression
w_watch(env:String, exp:String)
#Add an expression widget button
w_button(text:String, env:String, exp:String)
#Add a widget to monitor performance
w_perf
# Show all widgets plans
w_plans
#Save current widgets as a new plan
w_save_as(plan:String)
#Clear current widgets and load a plan
w_load(plan:String)
#Delete a widgets plan (Except for current plan)
w_delete(plan:String)
```
- When you add or remove a widget by clicking the close button right in the widget, the plan will be automatically saved.
- When quitting the current plan is memorized and will be loaded next time.

**Comment by scriptsengineer** [comment]
I created a simplified version of this in my current game, I'll share the code here in case I have something useful to extract from it:
https://gist.github.com/scriptsengineer/6893735e0a5b3025014abed00c09f7f7

**Comment by scriptsengineer** [comment]
![image](https://user-images.githubusercontent.com/1673249/203834128-797bc665-e976-45b7-9fe3-3f9d9ff2df07.png)

**Comment by scriptsengineer** [comment]
If placed as single I can just call it like this:
For func:
Stats.add_callable("TEST: ", Callable(Engine, "get_frames_per_second"))
For variable:
add_callable("TEST: ", obj, "variable_name")

**Comment by Ark2000** [comment]
> I created a simplified version of this in my current game, I'll share the code here in case I have something useful to extract from it: https://gist.github.com/scriptsengineer/6893735e0a5b3025014abed00c09f7f7

great reference

**Comment by Ark2000** [comment]
The v1.1 version should be released after some minor fixes.

**Comment by Ark2000** [comment]
Commit: https://github.com/Ark2000/PankuConsole/commit/971a70af3f6ba94dc974bbb262383c497fecabb8
