### ISSUE TITLE
Incosistent configuration saving/loading

### ISSUE THREAD

**Issue by Eggbertx** [Ark2000/PankuConsole#121]
**Describe the bug**
Panku Console seems to be inconsistently loading and saving its configuration. For example, enable_os_window can be set in the settings window, but its value is ignored if set in panku_config.cfg. Also, some of the names shown in the settings window are not the same in the configuration file. For example, `window_blur_effect` is stored as `lynx_window_blur_effect`, and `common_settings` is stored as `general_settings`

**Expected behavior**
Consistent label/configuration key names, all changes made in the configuration window should cause the configuration to be saved to the file.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Godot version 4.1.1

**Comment by Ark2000** [comment]
Thank you for reporting this issue. I appreciate you taking the time to provide these details.
Regarding the inconsistent configuration loading/saving, I tested the latest commit and was able to successfully change 'enable_os_window' both through the settings UI and by editing 'lynx_window_enable_os_window' in the config file. Can you confirm you are testing with the latest commit? If so, the related loading/saving logic is in 'panku_console/modules/general_settings/module.gd'. Please let me know if you have any other de
tails that could help me reproduce or debug this.
As for the naming inconsistencies between the UI and config file, I agree this could be improved. I plan to align these names in a future update. If you would like to submit a pull request to address this, I would welcome it.
Please let me know if you have any other questions! I appreciate you taking the time to report these issues as it will help improve the project.

![1](https://github.com/Ark2000/PankuConsole/assets/21126555/f99be814-bdd8-40cd-87eb-0c5330240c93)
![2](https://github.com/Ark2000/PankuConsole/assets/21126555/ca52aad0-59fc-451c-9ab5-72a98be3dd7d)

**Comment by Eggbertx** [comment]
Oh, I think I see what's going on. This line
https://github.com/Ark2000/PankuConsole/blob/7e2cb1c285ed6ad6519535cd46a010133e2d3728/addons/panku_console/console.gd#L69
Is called if the main OS window is closed by clicking on the close button or pressing Alt+F4, but not if the project using PankuConsole calls `get_tree().quit()` or Godot crashes. I forked the project and can work on the labels, and if it's alright with you, I'll see if I can get it to auto-save whenever a setting is changed. That way, changes are saved whether the game is exited via `get_tree().quit()` being called, the window being closed, or Godot crashing
