### ISSUE TITLE
Download from Godot AssetLib improper.

### ISSUE THREAD

**Issue by JeanKouss** [Ark2000/PankuConsole#122]
### Description
I am experiencing an issue while trying to install PankuConsole through the AssetLib panel in the Godot editor. The files I'm getting from the installer and their organization are different from what is expected based on the repository's content.

### How To Reproduce
1. Go to AssetLib panel ;
2. Search for "PankuConsole" ;
3. Attempt to install it.

### Expected behavior
When installing PankuConsole, the asset installer should provide the files that are consistent with the released version available in the repository.

### Screenshots
![image](https://github.com/Ark2000/PankuConsole/assets/70731505/dced4853-a74b-4c19-b672-1277bf2839e1)

### Infos
 - OS : Windows 10
 - Godot Version : v4.1.1.stable.official [bd6af8e0e]

**Comment by Ark2000** [comment]
Confirmed. Will be fixed later.

**Comment by Ark2000** [comment]
a new git branch `godot4_asset_library` is created, downloading from asset library should be ok now.
