### ISSUE TITLE
autocompletion options don't fit in their line 

### ISSUE THREAD

**Issue by mieldepoche** [Ark2000/PankuConsole#123]
**Describe the bug**

![Screenshot from 2023-08-03 19-08-09](https://github.com/Ark2000/PankuConsole/assets/71937306/a7ffd43e-c6f3-4396-b4aa-f4a654e5ea3e)

as you can see in this screenshot, the autocompletion proposals don't fit in their allocated spaces (notice how parentheses and Ps get cut, underscores are thus not visible), and a scrollbar appear on the side.
It doesn't seem to depend on the game's window stretch mode. I tested with an empty project and the problem's still here.

**To Reproduce**
1. run a game
2. spawn the console

**Desktop**
 - OS: ubuntu
 - godot 4.1
 - PankuConsole 7e2cb1c285ed6ad6519535cd46a010133e2d3728 (latest to this date)

**Comment by Ark2000** [comment]
it should be ok now

**Comment by mieldepoche** [comment]
yep fixed, thanks!
