### ISSUE TITLE
Add a side menu to the dev console

### ISSUE THREAD

**Issue by Ark2000** [Ark2000/PankuConsole#137]
**Is your feature request related to a problem? Please describe.**
No, there's not a related specific problem.

**Describe the solution you'd like**
I would like to add a side menu to dev console, since dev console is the most frequently used part of the plugin, and it is a little over simpified, we can add some entrances lead to other functionalities to increase convenience and intuitiveness,

**Describe alternatives you've considered**
People can always access other modules by typing commands, but sometimes this is not what we want.

**Additional context**
<img width="640" alt="1" src="https://github.com/Ark2000/PankuConsole/assets/21126555/2df3851f-c9fe-44ee-adcf-587c97360f97">
<img width="640" alt="2" src="https://github.com/Ark2000/PankuConsole/assets/21126555/a2e29d0e-9011-4b4b-a432-d5e92272cd43">

Here you can see, the side menu can be folded/unfolded by pressing the top left button.
Each button contains an expression which will be executed when the button gets clicked.

![image](https://github.com/Ark2000/PankuConsole/assets/21126555/1eba86c7-0670-4dc4-a3ad-e74257d5098d)
The buttons can be edited through configuration file located at res://

**Comment by Ark2000** [comment]
How do you guys like it? You can test it by the feat branch.
@scriptsengineer @mieldepoche @Eggbertx @univeous @CheapMeow @winston-yallow

**Comment by Eggbertx** [comment]
I like it, being able to access modules by clicking on the respective button instead of having to know the command is pretty convenient. And being able to switch between icon and icon+text mode is also pretty nice, especially for smaller viewports.

**Comment by winston-yallow** [comment]
oh heck yes! I'm a bit late to reply, but I love this new feature :blue_heart:
