### ISSUE TITLE
Settings > native_logger > font_size does not change any font sizes

### ISSUE THREAD

**Issue by Dustin00** [Ark2000/PankuConsole#144]
When you change Settings > native_logger > font_size, nothing appears to get changed.

You can change to 18, close and re-open, the new value is still there, but no font sizes are different.

Repro steps:
1. Run your app
2. Open Panku > Settings > native_logger > font_size
3. Set the value for font_size to 18
4. Close your app
5. Re-launch your app and re-open Panku

Result:
Font size of Panku is not changed
If you re-open the native_logger settings, you will see the value still set at 18

Expected:
Font size of Panku UI to be 18

Environment:
Windows 10
Godot 4.2.Stable

**Comment by Ark2000** [comment]
https://github.com/Ark2000/PankuConsole/assets/21126555/e7eaeda0-847e-4295-b125-3bff9d12994e

It works fine here.

**Comment by Dustin00** [comment]
Confirmed.

I see, I was really hoping it controlled font size for the overall UI of the tool -- I'm old now.
