### ISSUE TITLE
missing instruction on how to pop out OS window

### ISSUE THREAD

**Issue by CIOSAI** [Ark2000/PankuConsole#160]
**Is your feature request related to a problem? Please describe.**
I couldn't find how to pop out an OS window as shown in the README sample image.

![991256520400588810](https://github.com/Ark2000/PankuConsole/assets/89374056/57df334e-2472-44d8-9656-4d79058e0576)

**Describe the solution you'd like**
Put the instruction somewhere in the docs. (settings → general_settings → `enable_os_windows` → click the icon on top right)

**Comment by Ark2000** [comment]
![image](https://github.com/Ark2000/PankuConsole/assets/21126555/872cc05d-fed7-40a6-9e41-b56c0aa14041)

a detailed description will be added to docs later.

**Comment by Ark2000** [comment]
61faa99b371e1993a1667297511d9da255ec0774
