### ISSUE TITLE
Timestamps for Logger Output

### ISSUE THREAD

**Issue by Hotklou2404** [Ark2000/PankuConsole#163]
I was thinking that perhaps you could add an option to add timestamps to each line of the logger output.

**Comment by Ark2000** [comment]
Well, it's a simple feature that can be easily achieved with wrapper functions. Maybe later I will implement that and add an option to toggle logger timestamps (will be false by default).

**Comment by Ark2000** [comment]
![image](https://github.com/Ark2000/PankuConsole/assets/21126555/54ca2cbc-889f-41fd-98fd-b218398a03df)

Done.

The timestamps will only be shown within the embedded logger, the engline log file will remain untouched.

**Comment by Ark2000** [comment]
Sorry for the late replay, someone please give it a test, so I can close this issue.
