### ISSUE TITLE
Running crashes on Android.

### ISSUE THREAD

**Issue by Abab-bk** [Ark2000/PankuConsole#164]
**Describe the bug**
I exported my game to Android, but it crashes. Additionally, I didn't see the "disable on release" option in the project settings.

**To Reproduce**
1. Enable Plugin.
2. Export to Android.

**Expected behavior**
Disable plugin or running.

**Screenshots**
![image](https://github.com/Ark2000/PankuConsole/assets/55276676/89087a79-0d30-44cd-a617-7c7ab657a18c)
![image](https://github.com/Ark2000/PankuConsole/assets/55276676/c1a15728-0efa-42f9-a80c-6c0c1ebc49c6)

**Desktop (please complete the following information):**
 - Device: Redmi 12
 - OS: Android 14 / HyperOS
 - Version Godot 4.2.1 Stable, Panku Console 1.7.7.

**Comment by Ark2000** [comment]
Solution 1:

Go to project settings -> enable file logging, this may works.

![image](https://github.com/Ark2000/PankuConsole/assets/21126555/b3b4525f-8cd8-40f0-abe9-b873f139dc41)

Solution 2:

> I didn't see the "disable on release" option in the project settings.

This is a known issue, just go to plugins and then enable again, you will find the 'disable on release' setting. 

![image](https://github.com/Ark2000/PankuConsole/assets/21126555/72adfd66-57c6-4a9a-9dc8-45fd28610a3d)

**Comment by Abab-bk** [comment]
I've enabled it many times, but still no "disable on release"
![image](https://github.com/Ark2000/PankuConsole/assets/55276676/2b166666-caa1-4482-bcd0-c613a568b419)

**Comment by Ark2000** [comment]
> I've enabled it many times, but still no "disable on release" ![image](https://private-user-images.githubusercontent.com/55276676/307224571-2b166666-caa1-4482-bcd0-c613a568b419.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NjUyNTYsIm5iZiI6MTcwODY2NDk1NiwicGF0aCI6Ii81NTI3NjY3Ni8zMDcyMjQ1NzEtMmIxNjY2NjYtY2FhMS00NDgyLWJjZDAtYzYxM2E1NjhiNDE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA1MDkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NzY2NWQwOWNkZmM4NjIyNDlhM2VkMTZmZTk2YjYxYjBmNTJlMmQyODM1OTY3M2YxODBkMThhYmNkOTMwODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uNuUCEVY5gBum1yitUiHjUnylOjd-Yj-owLTbmQzlBk)

the search result wouldn't update unless the keyword is changed.

**Comment by Ark2000** [comment]
the panku project settings will be fixed soon.
