### ISSUE TITLE
The main font is very big for pixelarts games

### ISSUE THREAD

**Issue by MatiasVME** [Ark2000/PankuConsole#165]
**Is your feature request related to a problem? Please describe.**

I have a pixel art 390 x 220 game and I would like to use this plugin :( but inside the game and the console title font is too big. Is it possible to add an option for pixel art games ?? in which the console uses less resolution =S

**Describe the solution you'd like**
Adding new fonts, icons or panels that support pixel art

**Additional context**
I leave a video of how my game looks like :(

https://github.com/Ark2000/PankuConsole/assets/342117/09b2b597-551e-442b-a761-c3c766ac793b

**Comment by Ark2000** [comment]
I see, a pixel art game friendly ui design will be implemented later. For now, maybe you can increase the override window size and set stretch mode to none like this below.

![image](https://github.com/Ark2000/PankuConsole/assets/21126555/dd5706a3-0843-4d79-b0ab-1e2a2929ef3e)

![image](https://github.com/Ark2000/PankuConsole/assets/21126555/27af806d-0216-4fa6-9fec-ccea778caa85)

**Comment by MatiasVME** [comment]
thanks for your reply :) is good project 👍🏻

**Comment by Ark2000** [comment]
Closed. Related issue: #166
