### ISSUE TITLE
Ability to Increase All UI Size

### ISSUE THREAD

**Issue by alijaya** [Ark2000/PankuConsole#166]
**Is your feature request related to a problem? Please describe.**
In my game, the UI of Panku is really small, I can not read it.

**Describe the solution you'd like**
I hope there's a setting to adjust  UI scale.

**Comment by tarwich** [comment]
Since OP didn't provide a screenshot, I will.

<img width="1136" alt="image" src="https://github.com/Ark2000/PankuConsole/assets/334149/33359cb5-5470-4aec-af1b-31945d419f1a">

I'm pretty sure this is a PPI setting or something, but I'm not sure where to find it. Which is how I wound up here.

**Comment by Ark2000** [comment]
I'll prioritize fixing UI issues once I have enough free time.

**Comment by tarwich** [comment]
Well, I'll reiterate what many have said. You'd made an awesome plugin. It's exactly what I would've wanted. Thanks for sharing with the world!

**Comment by Ark2000** [comment]
> Well, I'll reiterate what many have said. You'd made an awesome plugin. It's exactly what I would've wanted. Thanks for sharing with the world!

Thank you! Working on UI related issues now

**Comment by Ark2000** [comment]
![image](https://github.com/Ark2000/PankuConsole/assets/21126555/be3ae842-ea8e-49f4-ae65-38b40d2f4100)
![image](https://github.com/Ark2000/PankuConsole/assets/21126555/3f52918e-2e28-4a4c-9f0a-b6c13527056d)

**Comment by Ark2000** [comment]
> Well, I'll reiterate what many have said. You'd made an awesome plugin. It's exactly what I would've wanted. Thanks for sharing with the world!

Thank you! It's people likecyou keep me motivated!

**Comment by FabriceCastel** [comment]
Weyooo thanks for tackling this @Ark2000 - stoked to get to actually use the console and add a bunch of debugging commands to it 😎 :shipit:

**Comment by tarwich** [comment]
<img width="1136" alt="image" src="https://github.com/Ark2000/PankuConsole/assets/334149/32c1ab98-0a78-443a-b93f-677cd70c1f64">

Scale is working much better for me. I am having to change all my resources because apparently I scaled them wrong for my DPI, but at least everything is manageable now.

This console has been a lifesaver for testing specific scenarios.

**Comment by alijaya** [comment]
Damn nice, will try it soon XD, thank you so much @Ark2000 , you made a god damn nice plugin that will be on my every Godot Project XD
