### ISSUE TITLE
The console wasn't using its own UI theme

### ISSUE THREAD

**Issue by CoderJo-Pro** [Ark2000/PankuConsole#169]
**Describe the bug**
As the title says. I seek through panku console's folder, and I saw there's a theme and a font resource, but never used. Because I'm using my own theme resource, and this theme's font is a pixel font. (my project's font is set by theme instead of the project settings)
It font referencing is weird. some is my pixel font, and some is its own modern font.

**To Reproduce**
1. Create a theme resource
3. Set it to `ProjectSettings`:`gui/theme/custom`
4. Override Label style (change some for example` font color` and `font size`) of the theme
5. Run whatever scene you have
6. Open the panku console and you'll see the console is somewhat strange

**Expected behavior**
it just uses its own theme resource, and user's (me) original project changes won't effect its appearance.

**Screenshots**
![Snipaste_2024-04-05_15-51-58](https://github.com/Ark2000/PankuConsole/assets/157453746/16ec267e-4342-4b42-8d3b-22ffc435f802)
this project had been upload on [itch.io](https://coderjo-pro.itch.io/juicy-jump)

**Comment by Ark2000** [comment]
Well, currently fonts resources are scattered around different scenes.

For now, if you want to change the output fonts:
1. go to `panku_console_ui.tscn`
2. find the node `RichTextLabel`
3. change its fonts theme overrides, done.

![image](https://github.com/Ark2000/PankuConsole/assets/21126555/f47a7833-4cd0-4e5e-be69-1e1c652da70f)

![image](https://github.com/Ark2000/PankuConsole/assets/21126555/84164575-b222-4ba3-864a-fe96e5496f58)

Thanks for your feedback, I will work on UI issues later.

**Comment by CoderJo-Pro** [comment]
well I think you can just make your root window control node to use the console's theme.
this will make the children inherits the theme from window root, no origin project changes will effect panku console.

this is my simple thought for improvement :P

**Comment by Ark2000** [comment]
Closed. Related issue: #166
