### ISSUE TITLE
Make Panku disabled on release builds

### ISSUE THREAD

**Issue by clement-or** [Ark2000/PankuConsole#170]
I thought the plugin would deactivate itself when making a release build, but it doesn't. It should be as easy as adding something like this on console's instantiation :

```gdscript
if OS.has_feature("release"):
    # Disable Panku
```

**Comment by worron** [comment]
Did you enable special option `Project->Project Settings->Panku->Disable on release`?

**Comment by clement-or** [comment]
No, I didn't know it existed, but imo should be enabled by default

**Comment by Ark2000** [comment]
> No, I didn't know it existed, but imo should be enabled by default

Suggestion accepted.

https://github.com/Ark2000/PankuConsole/blob/master/docs/faq.md
Maybe I should work on something like a dedicated doc website later.

**Comment by clement-or** [comment]
Thanks for the quick and positive response. Love the addon btw, it's in all of my projects
