### ISSUE TITLE
Make the native logger "show if shell visible" setting default.

### ISSUE THREAD

**Issue by TheContainer** [Ark2000/PankuConsole#173]
**Is your feature request related to a problem? Please describe.**
I really want to leave the console in the exported build. But the problem is, the logger is always visible by default. I could just change the settings, but these are stored in the user folder, which means that they don't transfer across devices.

**Describe the solution you'd like**
Make the native logger "show if shell visible" setting default.

**Comment by Ark2000** [comment]
I've got a better plan, now a default config file will be added to the plugin's folder, what do you think of it?

**Comment by TheContainer** [comment]
> I've got a better plan, now a default config file will be added to the plugin's folder, what do you think of it?

That is even a better idea and would perfectly.

**Comment by worron** [comment]
> I've got a better plan, now a default config file will be added to the plugin's folder, what do you think of it?

I'm afraid it might have a negative impact on git submodule routine, which I consider as very valuable feature of panku plugin. User settings should not affect git status of your project, and it works perfectly right now.

Obvious workaround is to make panku config file path customizable in godot project settings. Not sure if is it easy to implement though.

**Comment by Ark2000** [comment]
ok, now a rough solution is:

whenever `load_module_data` is called, such as `load_module_data("show_timestamp", true)`

**[start]**

1. find config file in `user://` folder, if not found, go to step 2
2. find config file in developer specified `res://` folder (in project settings), if not found, go to step 3
3. use the default value provided in function call.

**[quit]**

save everything to `user://` folder config file.
