### ISSUE TITLE
Console doesn't scale its size to respond to high DPI displays

### ISSUE THREAD

**Issue by FabriceCastel** [Ark2000/PankuConsole#174]
**Describe the bug**
The console renders at a fixed px resolution, which ends up causing a ["what is this, a UI for ants?"](https://knowyourmeme.com/memes/what-is-this-a-center-for-ants) situation whenever you use a higher DPI display (in my case, a macbook with a retina display, 250dpi vs. a standard display that would have approx 96dpi)

**Expected behavior**
Panku console UI adjusts to the display DPI to retain a consistent perceived scale.

**Screenshots**
<img width="1728" alt="image" src="https://github.com/Ark2000/PankuConsole/assets/2886675/77515f0b-1f44-4fac-9142-2a8fe563bb19">

**Comment by Ark2000** [comment]
https://docs.godotengine.org/en/stable/tutorials/rendering/multiple_resolutions.html

**Comment by Ark2000** [comment]
Closed. Related issue: #166
