### ISSUE TITLE
The default panku config does not apply when exported

### ISSUE THREAD

**Issue by TheContainer** [Ark2000/PankuConsole#179]
**Describe the bug**
After exporting the project, the Panku console completely ignores the default config. This issue was tested on the logger visibility setting (`screen_overlay`). I configured it in the file to have an index of 1, which corresponds to "show if shell visible". The project works correctly in the editor, but upon export, the logger always remains visible.

**To Reproduce**
1. Create a project with the addon.
2. Modify the default config.
3. Export the project.

**Desktop:**
 - OS: Windows 10 Pro
 - Godot v.4.2.2
 - PankuConsole v.1.7.8

**Additional information**
 Reading the config from the user data folder continues to function correctly in both the exported and editor projects.

**Comment by worron** [comment]
Just in case, have you done configuration in export template to include config files to the build?
In export page `Resources` tab -> 'Filters to export non-resource files' field. General mask like `*.cfg` or certain file name should work.
