### ISSUE TITLE
Config loading does not work in exported projects in 1.7.8

### ISSUE THREAD

**Issue by smedelyan** [Ark2000/PankuConsole#180]
Subj. Config does not get loaded and windows (e.g. native logger, expressions, history, etc.) are being opened automatically on start.

This seems to be the bug in 1.7.8. With 1.7.7 I don't have such problems

**To Reproduce**
1. Add v1.7.8 plugin to the project, export project and run `*.console.exe` to see errors
2. Console has parse errors reported for panku code
3. Project launches with panku windows opened and stacked in top-left one on top of the other

**Expected behavior**
No warnings, project loads without panku windows all opened.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 1.7.8

**Comment by Ark2000** [comment]
Could you please provide more information about the reported errors? I'll give it a test later.

**Comment by francoisdlt** [comment]
*.cfg files are not included by default in the export templates. I've had to manually add the default preset cfg file in the include_filter of my export config.

**Comment by Ark2000** [comment]
EditorExportPlugin is buggy, so it will be removed temporarily.

https://github.com/godotengine/godot/issues/73525

**Comment by Ark2000** [comment]
> *.cfg files are not included by default in the export templates. I've had to manually add the default preset cfg file in the include_filter of my export config.

Are you saying that this file is not accessible in exported project by default?
```
const INITIAL_DEFAULT_CONFIG_FILE_PATH = "res://addons/panku_console/default_panku_config.cfg"
```
