### ISSUE TITLE
Can't access the website

### ISSUE THREAD

**Issue by Minoqi** [Ark2000/PankuConsole#181]
**Describe the bug**
When trying to open the website it says:

> This site can’t provide a secure connection
> k2kra.xyz sent an invalid response.
> ERR_SSL_PROTOCOL_ERROR

**To Reproduce**
1. Click the link

**Expected behavior**
Correctly loading the website

**Screenshots**
![CleanShot 2024-07-23 at 13 50 40@2x](https://github.com/user-attachments/assets/1c02067c-9cd9-4fd6-a8fd-68ff81544e00)

**Desktop (please complete the following information):**
 - OS: Mac - Sonoma 14.5
 - Browser: Arc + Safari

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 17.5.1
 - Browser: Safari

**Comment by Ark2000** [comment]
What about try out this?
https://ark2000.github.io/PankuConsole

**Comment by Minoqi** [comment]
> What about try out this? https://ark2000.github.io/PankuConsole

I get the same error

**Comment by Ark2000** [comment]
The website will be reformed later.
