### ISSUE TITLE
Opening / closing the console unpauses the game

### ISSUE THREAD

**Issue by smedelyan** [Ark2000/PankuConsole#184]
**Describe the bug**
Hi. I noticed that when I open and close the console while staying in GUI (e.g. in my Pause menu which pauses the game), the game unpauses. Presumably, because the console does not check whether the tree was paused already when the console popped up - and does not restore that initial state. Can we add something like this?

**To Reproduce**
1. Open your game and make the tree paused (e.g. open pause menu or similar)
2. Open PankuConsole, close PankuConsole
3. The game unpauses.

**Expected behavior**
The game stays on pause

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by worron** [comment]
Do you use the latest version of console? This issue was addressed in #161, if I understand it correctly.

**Comment by smedelyan** [comment]
No, I'm using v`1.7.7`, but that version was released long after that fix was merged?

**Comment by worron** [comment]
The fix belong to [v1.7.8](https://github.com/Ark2000/PankuConsole/releases/tag/v1.7.8) according the log, I recommend to update .

**Comment by smedelyan** [comment]
Got it, thank you! Let's close the issue? I will try to check this out later
