### ISSUE TITLE
`current` is set to Window node after using OS window mode

### ISSUE THREAD

**Issue by heppocogne** [Ark2000/PankuConsole#206]
**Describe the bug**
Maybe related to #171.

`current` variable of interactive shell is set to Window node when using OS window mode.
When this problem happens, the correct `current` node will be unavailable until current scene is switched, reloaded or the game is restarted.

(note)
I inserted `print_debug` and found that `func _get_valid_root_nodes() -> Array` in [modules/variable_tracker/module.gd](https://github.com/Ark2000/PankuConsole/blob/69fdd0d39fc3e8b2125e7d0b25fa4d3e1765c6b7/addons/panku_console/modules/variable_tracker/module.gd) returned:
`[@Window@36:<Window#172905991182>, Main:<Node3D#74255959313>, ...]`

**To Reproduce**
1. launch game
2. open PankuConsole
3. open any tools in OS window mode
4. `current` node is set to Window node

**Expected behavior**
`current` should be same as `current_scene` of game

**Screenshots**
![bug_1](https://github.com/user-attachments/assets/a194cbd5-ecb2-4a4c-a3c1-568cb01d703a)
![bug_2](https://github.com/user-attachments/assets/be0d5f23-eaa3-434e-8848-45f7cb4ccda6)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version: 23H2

**Additional context**

**Comment by worron** [comment]
Thanks for report. If you need quick temporary solution right now, you can add 'Window' match to panku settings -> `variable_tracker` -> `root_node_exceptions` field. We will add os windows to exceptions by default in the future.
