### ISSUE TITLE
Compilation error if plugin disabled

### ISSUE THREAD

**Issue by smedelyan** [Ark2000/PankuConsole#212]
**To Reproduce**
1. Disable Panku (this will remove `Panku` singleton)
2. See errors in Godot output (you may need to restart the editor) that `Panku` is not defined (e.g. at `row_ui_comment.gd:8`)

**Comment by worron** [comment]
Confirmed, we will investigate this, thanks for report.

**Comment by smedelyan** [comment]
If that helps, for myself I just added a `static var _instance: PankuConsole` which I'm assigning in its `_init()`
