### ISSUE TITLE
The console window should be able to be an independant OS window.

### ISSUE THREAD

**Issue by Ark2000** [Ark2000/PankuConsole#23]
Multi windows is a notable new feature of Godot 4 that we can utilize.

Just like this: https://www.youtube.com/watch?v=iKoYbtw4gC0&t=249s

If we have multiple screens, the console window then will not occupy the precious space of the game screen.

**Comment by Ark2000** [comment]
This will be implemented when the Godot 4 docs is ready.

**Comment by Tsotsi** [comment]
it would be a cool feature

**Comment by Ark2000** [comment]
https://user-images.githubusercontent.com/21126555/221360774-c9f717cf-4167-45d9-bd5c-6feedd193da0.mp4

Experimenting with multiwindows. I'm using `get_viewport().gui_embed_subwindows = false` to create os window, are there any better ways?

**Comment by Ark2000** [comment]
<img width="208" alt="1" src="https://user-images.githubusercontent.com/21126555/221497479-cb3dd1c7-7bcf-4021-a595-eaacfe4e8a28.png">

add two new options, if you enable this, a third button will appear on the top right corner of a window.

<img width="640" alt="2" src="https://user-images.githubusercontent.com/21126555/221497487-dd651917-dca6-4bdd-b22b-7f3be2961eec.png">

By clicking that button, you will be able to switch to os window.

<img width="640" alt="3" src="https://user-images.githubusercontent.com/21126555/221497489-4033f9e6-60a6-4424-b0db-f878101d9bb4.png">

if you close the os window, it will sit back to its original position.
