### ISSUE TITLE
Cyclic dependency with DefaultEnv inside console.tscn

### ISSUE THREAD

**Issue by scriptsengineer** [Ark2000/PankuConsole#27]
![image](https://user-images.githubusercontent.com/1673249/204149901-5d226de6-63d4-4e8f-ba49-c04670c21e96.png)

**Comment by scriptsengineer** [comment]
Happens sometimes, it maybe depends on the scripts startup order

**Comment by Ark2000** [comment]
Maybe we should relocate this line from `default_env._ready()` to `console._ready()` ?

```gdscript
Console.register_env("default",self)
```

Not sure about that.

**Comment by Ark2000** [comment]
I update the Godot version from Godot beta 4 to Godot beta 6, now I see the errors every time.

**Comment by Ark2000** [comment]
replace `Console` with `get_parent()` in `default_env.gd` solves this.

**Comment by Ark2000** [comment]
It was caused by an Engine bug and was fixed in Godot 4 Beta 7: https://github.com/godotengine/godot/pull/69079
