### ISSUE TITLE
Add a minimal mode for REPL

### ISSUE THREAD

**Issue by Ark2000** [Ark2000/PankuConsole#53]
like this below, only input box and hints are showed in the center.
This is great for its simplicity.
And you can switch between full/minimal mode very easily.
![image](https://user-images.githubusercontent.com/21126555/210596667-c3d90700-e8f6-4ce4-9dd8-708dd923ba11.png)

**Comment by Ark2000** [comment]
Done, looks good to me.

![image](https://user-images.githubusercontent.com/21126555/210820257-17373809-f0a6-4a0c-ae5f-f6a8f24eb486.png)

**Comment by Ark2000** [comment]
I'd better take a rest now.

**Comment by alijaya** [comment]
Where is this feature? I can't find it :')

**Comment by Ark2000** [comment]
> Where is this feature? I can't find it :')

see https://github.com/Ark2000/PankuConsole/blob/master/docs/developer_console.md

> interactive_shell.open_launcher() Open the developer console minimized version, which only contains the input box and auto-completion.

**Comment by alijaya** [comment]
Oh I thought there's some button somewhere. So we need to execute this from code right? Thanks!
