### ISSUE TITLE
No need for a Panku.gd and Panku_impl.gd, currently Panku.gd does not contain any implementation

### ISSUE THREAD

**Issue by scriptsengineer** [Ark2000/PankuConsole#6]
I suggest that it contains only a file called panku.gd with the implementation that is in the panku_impl.gd file

**Comment by Ark2000** [comment]
In my option it will be clearer to only expose the interface functions, or is it a convention to put everything into a single file in Godot singletons?

**Comment by scriptsengineer** [comment]
I don't believe there is a pattern with autoloads, but following a SOLID principle, I can't see what purpose the panku.gd class has
Do you have an example in godot of a structure that uses subclass as an interface?

**Comment by Ark2000** [comment]
This pointless script will be removed later when the docs is finished.
