### ISSUE TITLE
Add ability to monitor textures

### ISSUE THREAD

**Issue by winston-yallow** [Ark2000/PankuConsole#65]
It would be awesome to show the texture if monitoring one. This would be especially useful when monitoring ViewportTextures, as this would be a quick way to check what the sub viewport is currently rendering.

**Comment by Ark2000** [comment]
Great idea!

**Comment by Ark2000** [comment]
done

**Comment by winston-yallow** [comment]
Heck yeah, thanks!

Here's the addon in use, the texture is a simulation of how far the plants have spreaded through the streets. The new feature makes it super easy to monitor it 🎉 

![image](https://user-images.githubusercontent.com/44872771/215156136-787bfa85-51eb-4869-a178-1ba3e6e43b21.png)
