### ISSUE TITLE
Add option to restore recent monitors

### ISSUE THREAD

**Issue by winston-yallow** [Ark2000/PankuConsole#66]
It would be cool to have a "recently used" menu to restore closed monitors^.

**Comment by Ark2000** [comment]
I have implemented monitor saves in recent commits, you can give it a try.

**Comment by Ark2000** [comment]
> If I didn't miss anything, then that is just restoring monitors from the last run. Which is really awesome in it's own! But what I'm suggesting is a menu to restore widgets that the user closed. I sometimes close widgets by accident, and especially if it was based on a complex expression it would be nice to easily restore it.

The suggestion reminds me the fact that it lacks ability to remember user input histories on disk, which is important.

**Comment by Ark2000** [comment]
I'll add a window to track input expression histories which you can copy and even edit, this should be a more general feature.

**Comment by winston-yallow** [comment]
Sounds good to me! Not sure how much effort it would be, but making it multi-select would make it easy to select a bunch of expressions and create monitors for all of them

**Comment by Ark2000** [comment]
This is the result, https://github.com/Ark2000/PankuConsole/issues/68
I'm pretty sure it will be very useful.

**Comment by winston-yallow** [comment]
That is really awesome! The only thing I would like to have would be a quick way to create monitors based on them. Maybe next to the "Copy" button there could be a "Monitor" button. That way it would be quick to create monitors without first going to the console and pasting the expressions. But that's just a minor convenience nitpick, it's already super useful
