### ISSUE TITLE
设置导出节点,自动显示全部属性

### ISSUE THREAD

**Issue by wayrboy** [Ark2000/PankuConsole#76]
![image](https://user-images.githubusercontent.com/15027345/218326495-f2df3e9b-e46b-40d1-b118-131c9b614136.png)

att文件
![image](https://user-images.githubusercontent.com/15027345/218326543-9caec160-cb12-473a-bc3a-4df0c4ef149e.png)

不然的话,得一个框一个框的新建,很是麻烦

**Comment by Ark2000** [comment]
You can write expression like this to monitor multiple variables.
`hp: %d\nmax_hp:%d\nattack:%d\ndefend:%d`

I may add a shortcut command to the default execution environment later.

**Comment by Ark2000** [comment]
![image](https://user-images.githubusercontent.com/21126555/222483956-57f3196e-0aea-491c-8585-730b91b018a3.png)

Add a new shortcut command to show all public script properties of an object.
